#!/bin/sh
set -o errexit
set -o nounset

for FILE in *; do
    DOTFILE="../.${FILE}"
    [ "${FILE}" = "script" ] && continue
    [ -d "${DOTFILE}" ] && rm -r "${DOTFILE}"
    ln -sf ".dotfiles/${FILE}" "${DOTFILE}"
done

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugInstall +qall
