#!/bin/sh
set -o errexit
set -o nounset

for FILE in *; do
    DOTFILE="../.${FILE}"
    [ "${FILE}" = "script" ] && continue
    [ -d "${DOTFILE}" ] && rm -r "${DOTFILE}"
    ln -sf ".dotfiles/${FILE}" "${DOTFILE}"
done

chmod 600 aws/credentials
chmod 700 gnupg

defaults write com.apple.screencapture location ~/Documents/Screenshots

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
vim +PlugInstall +qall

cp -a /System/Applications/Utilities/Terminal.app/Contents/Resources/Fonts/SF-Mono-* ~/Library/Fonts/

ln -sf /Applications/Docker.app/Contents/Resources/etc/docker.bash-completion /usr/local/etc/bash_completion.d/docker
ln -sf /Applications/Docker.app/Contents/Resources/etc/docker-compose.bash-completion /usr/local/etc/bash_completion.d/docker-compose
